import type { StampId } from "@/lib/stamps/keywordMap";

/** Short Korean label per keyword stamp, for the 우표 모아보기 ranking
 * board — nowhere else in the app names a keyword stamp in words, it's
 * always just shown as its icon. */
export const STAMP_LABELS: Record<StampId, string> = {
  rain: "비",
  sun: "맑음",
  snow: "눈",
  food: "식사",
  coffee: "커피",
  travel: "여행",
  study: "공부",
  sleep: "잠",
  exercise: "운동",
  music: "음악",
  book: "독서",
  joy: "기쁨",
  sad: "속상함",
  work: "일",
  cat: "고양이",
  flower: "꽃",
  celebration: "축하",
  shopping: "쇼핑",
  movie: "영화",
  phone: "통화",
  rest: "휴식",
  cook: "요리",
  dog: "강아지",
  cloud: "흐림",
  bread: "빵",
  calendar: "약속",
  chat: "수다",
  heart: "사랑",
  mountain: "산",
  ocean: "바다",
  rainbow: "무지개",
  tomato: "토마토",
  gimbap: "김밥",
  sushi: "초밥",
  bibimbap: "비빔밥",
  burger: "버거",
  pizza: "피자",
  salad: "샐러드",
  default: "그 밖의 하루",
};
